# Generated by Django 5.2.14 on 2026-09-25 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('crops', models.JSONField(blank=True, default=list)),
                ('land_size_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('farmer_category', models.CharField(blank=True, choices=[('small', 'Small farmer'), ('marginal', 'Marginal farmer'), ('tenant', 'Tenant farmer'), ('women', 'Women farmer'), ('other', 'Other')], max_length=20)),
                ('irrigation_type', models.CharField(blank=True, choices=[('rainfed', 'Rainfed'), ('canal', 'Canal'), ('borewell', 'Borewell'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('other', 'Other')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
