# Generated by Django 5.2.14 on 2026-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('state', models.CharField(blank=True, help_text='Blank means applicable across states.', max_length=80)),
                ('crops', models.JSONField(blank=True, default=list)),
                ('farmer_categories', models.JSONField(blank=True, default=list)),
                ('benefits', models.TextField()),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('application_process', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('official_source_url', models.URLField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline', 'name'],
            },
        ),
    ]
